//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LargeBank.API
{
    using Models;
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int CustomerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }

        // Update properties in Customer class from the input object
        public void Update(CustomerModel modelCustomer)
        {
            // If adding new customer, set created date
            if (modelCustomer.CustomerId == 0)
            {
                CreatedDate = DateTime.Now;
            }

            // Copy values from input object to Customer properties
            FirstName = modelCustomer.FirstName;
            LastName = modelCustomer.LastName;
            Address1 = modelCustomer.Address1;
            Address2 = modelCustomer.Address2;
            City = modelCustomer.City;
            State = modelCustomer.State;
            Zip = modelCustomer.Zip;
        }
    }
}
