//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LargeBank.API
{
    using Models;
    using System;
    using System.Collections.Generic;

    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int AccountId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }

        // Update properties in Transaction class from the input object
        public void Update(TransactionModel modelTransaction)
        {
            // Copy values from input object to Transaction properties
            AccountId = modelTransaction.AccountId;
            Amount = modelTransaction.Amount;
            TransactionDate = modelTransaction.TransactionDate;
            TransactionId = modelTransaction.TransactionId;
        }
    }
}
